#=============================================================================
#  wifi
#=============================================================================
obj-$(CONFIG_HW_WIFI) += ipv4/
obj-$(CONFIG_HW_BOOSTER) += booster/
EXTRA_CFLAGS += -Idriver/huawei_platform
