obj-y += cpu_netlink.o
obj-$(CONFIG_HW_VIP_THREAD) += proc_fork_nl.o
obj-$(CONFIG_HW_RTG_SCHED) += proc_comm_nl.o

obj-$(CONFIG_HW_CGROUP_WORKINGSET) += cgroup_workingset.o
obj-$(CONFIG_DETECT_HUAWEI_HUNG_TASK) += huawei_hung_task.o
obj-$(CONFIG_HUAWEI_INIT_WATCHDOG) += huawei_init_watchdog.o
