obj-$(CONFIG_HISI_SLOW_PATH_COUNT) += slowpath_count.o
obj-$(CONFIG_HISI_PMALLOC) += pmalloc.o
obj-$(CONFIG_HISI_QOS_MEM_OPT) += qos_mem.o
obj-$(CONFIG_HUAWEI_UNMOVABLE_ISOLATE) += unmovable_isolate.o
obj-$(CONFIG_HISI_PAGECACHE_HELPER) += pagecache_manage.o
