#!/usr/bin/env bash

# output will be overwritten on each run.
# definition should have the following format:
# #define XXX_MAGIC 0xaabbccdd
# ...
# <files> should be named as inlinehook_YYY.bin.
#
# Generated output is like:
# #define YYY_XXX_OFFSET <value>

if [ $# -lt 3 ]; then
    echo "$0: output definition <files>"
    exit 1
fi

out=$1
shift
def=$1
shift

# test for working path
touch ${out}
if [ -z ${out} -o ! -f ${out} ]; then echo "$0: no output"; exit 1; fi
if [ -z ${def} -o ! -f ${def} ]; then echo "$0: no definition"; exit 1; fi

get_off() {
    _out=$1
    _src=$2
    _key=$3
    _mem=$4

    off=$(python - "$_src" "$_mem" <<'PY'
import sys, struct

src = sys.argv[1]
mem = int(sys.argv[2], 16)

needle = struct.pack("<I", mem)

with open(src, "rb") as f:
    data = f.read()

idx = data.find(needle)
if idx >= 0:
    print(idx)
PY
)

    if [ -n "$off" ]; then
        echo "#define ${_key} ${off}" >> "${_out}"
    fi
}

gen_off() {
    _def=$1
    _bin=$2
    _out=$3
    what=`basename ${_bin} .bin | sed 's/inlinehook_//g' | tr a-z A-Z`
    grep "MAGIC" "${_def}" | while read d; do
        key=`echo $d | awk '{print $2}' | sed s/MAGIC/OFFSET/g`
        val=`echo $d | awk '{print $3}'`
        get_off ${_out} ${_bin} "${what}_${key}" ${val}
    done
}

echo "/* autogen */" > $out
while [ $# -ne 0 ]; do
    bin=$1
    gen_off ${def} ${bin} ${out}
    shift
done
