ccflags-y  += -I$(srctree)/drivers/contexthub/
obj-y += hisi_aod_device.o
EXTRA_CFLAGS += -Idrivers/huawei_platform/inputhub/kirin980\
		-Idrivers/video/fbdev/hisi/dss \
		-Idrivers/video/hisi/dss \
		-Idrivers/staging/android
