#=============================================================================
#  wifi
#=============================================================================

obj-$(CONFIG_HW_NETFILTER_MODULE) += hw_netfilter/

obj-$(CONFIG_HW_COMMSTAT) += commstat/

obj-$(CONFIG_HW_DC_MODULE) += hw_dual_connection/

obj-$(CONFIG_HW_NETBOOSTER_MODULE) += netbooster/

obj-$(CONFIG_HUAWEI_BASTET) += bastet/

